# For more information about stack's configuration, see
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
#
flags: {}
extra-package-dbs: []
packages: []
extra-deps: 
    - binary-shared-0.8.3
    - ghcjs-codemirror-0.0.0.1
    - ghcjs-dom-0.2.3.0
    - gtksourceview3-0.13.2.0
    - jsaddle-0.2.1.0
    - leksah-server-0.15.0.9
    - ltk-0.15.0.4
    - regex-tdfa-text-1.0.0.3
    - vado-0.0.5
    - vcsgui-0.1.3.0
    - vcswrapper-0.1.2
    - webkitgtk3-0.14.1.0
    - webkitgtk3-javascriptcore-0.13.1.0
    - attoparsec-conduit-1.1.0
    - mic-state-0.2.0.0
    - dynamic-state-0.2.0.0
    - dyre-0.8.12
    - oo-prototypes-0.1.0.0
    - pointedlist-0.6.1
    - vty-5.4.0
    - word-trie-0.3.0
    - xdg-basedir-0.2.2
    - yi-language-0.2.0
    - io-storage-0.3
    - yi-rope-0.7.0.1
    - charsetdetect-ae-1.1.0.1
    - cabal-helper-0.6.1.0
    - libmpd-0.9.0.4
    - xmonad-0.11.1
    - xmonad-contrib-0.11.4
    - X11-xft-0.3.1
    - vinyl-0.5.1
resolver: lts-3.12
