packages: []
resolver: lts-6.1
flags: {}
extra-package-dbs: []
# stack install ihaskell-aeson ihaskell ihaskell-blaze ihaskell-charts ihaskell-diagrams ihaskell-juicypixels ihaskell-magic hdevtools stylish-haskell ghc-mod hlint xmonad xmonad-contrib yesod-bin- X11-xft-0.3.1
extra-deps:
- X11-xft-0.3.1
- data-r-tree-0.0.5.0
- data-stringmap-1.0.1.1
- gtk-traymanager-0.1.6
- xmonad-contrib-0.12
