git_protocol: ssh
aliases:
    repo-sync-merge: |
        !
        REPO=hiyainc/$1
        PR=$(gh pr --repo "$REPO" list | grep "automated/repo-sync" | awk \{\ print\ \$1\ \})
        gh pr --repo "$REPO" checks  $PR || exit 1
        gh pr --repo "$REPO" review --approve $PR || exit 1
        gh pr --repo "$REPO" merge --squash $PR
version: "1"
