syntax on
filetype on
set colorcolumn=120
set cursorline
set expandtab
#set foldlevel=99
set history=1000
set ignorecase
set incsearch
set list
set listchars=tab:▸▸,trail:·
set number
set ruler
set shiftwidth=2
set showbreak=↪\ 
set showmode
set smartcase
set softtabstop=2
set timeout
set timeoutlen=400
set title
set tw=0
set wildignore+=*\\tmp\\*,*.hi,*.swp,*.swo,*.o,*.zip,.git,.cabal-sandbox,node_modules,.stack-work
set mouse=""

